use_frameworks!

platform :ios, '10.0'

target 'QiBackgroundRunning_Example' do
  pod 'QiBackgroundRunning', :path => '../'

  target 'QiBackgroundRunning_Tests' do
    inherit! :search_paths
  end
end
